### ISSUE TITLE
../@key doesn't work

### ISSUE THREAD

**Issue by dallasread** [Mike96Angelo/Bars#10]
../@key doesn't work to get the index of a parent loop.

**Comment by Mike96Angelo** [comment]
`lib/runtime/context.js` <- this is where to look to try and fix that bug.

**Comment by dallasread** [comment]
Thanks. I was mainly just adding the issue to remember to do it later. :)

**Comment by Mike96Angelo** [comment]
slash paths are no longer a feature.
