### ISSUE TITLE
When an element is removed from an array, it is re-rendered incorrectly.

### ISSUE THREAD

**Issue by dallasread** [Mike96Angelo/Bars#8]
When an element is removed from an array, the `_update()` logic is flawed. I think we're going to have to somehow keep track if each element in the array has changed and do some magical redrawing.

Logic is at [Bars/lib/frag.js#L310](https://github.com/Mike96Angelo/Bars/blob/master/lib/frag.js#L310).

**Comment by dallasread** [comment]
This was an err on my part!

**Comment by dallasread** [comment]
On second thought, the render was not working when I was re-setting the entire array, not just manipulating it. So this is where the issue occurs.

**Comment by Mike96Angelo** [comment]
@dallasread can you confirm that this is still an issue v0.9.0+

**Comment by Mike96Angelo** [comment]
Seems to have been fixed.
